### ISSUE TITLE
[Question] Request for clarification of some points

### ISSUE THREAD

**Issue by twiechert** [bakdata/streams-explorer#76]
Thanks for the nice work: I have a couple of questions I would like to clarify as we are considering to poc the streams explorer.

**Streams bootstrap chart/lib optional**
It is not actually required to use the streams bootstrap chart nor the streams library as long as our Deployments are labeled accordingly and expose the simplified topology via env variables. Right?

**Exporters needed to visualize simple pipeline**
Is the presence of all metrics really needed to build the first visualization of a pipeline? Especially the need for the connect exporter would not be justified in case Kafka Connect is even not used.

**Dataflow between Kafka stream apps visualized**
Consider two distinct kafka streaming apps, where the second one consumes the output of the first. Is that dataflow visualized accordingly or are two seperate "apps" without a connecting link ? 

**Replacing exporters**
As we use Burrow for lag monitoring, I wonder if we could plugin our own extractor for the lag metrics and if that is the case, I wonder where the appropriate place in the code would be at.

Other than that, I would like to understand which exact metrics are required so that we could potentially trick the streams explorer by rewriting our existing metrics to match the required ones.

**Use topology endpoint for topic extraction**
We'd prefer to read the topology dynamically through a REST endpoint exposed by our streaming apps instead of relying on env variables being set via Helm. Do you consider this a reasonable alternative plus could you give a hint where that logic would be supposed to be implemented?

Looking forward to response!

**Comment by disrupted** [comment]
Hi @twiechert! Thanks for your interest in our project, we are happy to follow up on your questions.

> **Streams bootstrap chart/lib optional**
> It is not actually required to use the streams bootstrap chart nor the streams library as long as our Deployments are labeled accordingly and expose the simplified topology via env variables. Right?

You’re right. Without using the streams-bootstrap Helm chart, you can set the same ENV variables for the Kubernetes deployment of your streaming application: We require the `ENV_PREFIX`, `INPUT_TOPICS` (comma-separated), `OUTPUT_TOPIC` variables (optional are `ERROR_TOPIC`, `EXTRA_INPUT_TOPICS`, `EXTRA_OUTPUT_TOPICS`). The value of `ENV_PREFIX` should prefix all variables, e.g. if `ENV_PREFIX: APP_` is set, we look for the `APP_INPUT_TOPICS` variable, and so on.

There is a separate blogpost about why we chose this setup method if you're interested: [Continuous NLP Pipelines with Python, Java, and Apache Kafka](https://medium.com/bakdata/continuous-nlp-pipelines-with-python-java-and-apache-kafka-f6903e7e429d)

> **Dataflow between Kafka stream apps visualized**
> Consider two distinct kafka streaming apps, where the second one consumes the output of the first. Is that dataflow visualized accordingly or are two seperate "apps" without a connecting link ?

The graph layout is created from the topology defined in the environment variables of the streaming application deployment. As long as the input topics and output topic of each application are set accordingly, the resulting connections should be displayed in the visualization.

> **Exporters needed to visualize simple pipeline**
> Is the presence of all metrics really needed to build the first visualization of a pipeline? Especially the need for the connect exporter would not be justified in case Kafka Connect is even not used.
> 
> **Replacing exporters**
> As we use Burrow for lag monitoring, I wonder if we could plugin our own extractor for the lag metrics and if that is the case, I wonder where the appropriate place in the code would be at.
> Other than that, I would like to understand which exact metrics are required so that we could potentially trick the streams explorer by rewriting our existing metrics to match the required ones.

Metrics provided by Prometheus and its exporters are not strictly required to start using Streams Explorer.  You can begin without it, but you might see an error in the logs that the connection to Prometheus cannot be established. The graph visualization will lack the metrics information.

Additionally based on your input we have opened an issue (https://github.com/bakdata/streams-explorer/issues/78) to add the current metrics provider to the existing plugin system. This will allow for setting up your own custom metric provider by implementing the [`MetricProvider`](https://github.com/bakdata/streams-explorer/blob/ffa3de270965c3f835fa1fd65e8817f66f3f8057/backend/streams_explorer/core/services/metric_providers.py#L47) interface (similar to the existing [`DefaultLinker`](https://github.com/bakdata/streams-explorer/blob/main/backend/streams_explorer/defaultlinker.py) plugin which extends the [`LinkingService`](https://github.com/bakdata/streams-explorer/blob/ffa3de270965c3f835fa1fd65e8817f66f3f8057/backend/streams_explorer/core/services/linking_services.py#L7) class).

As for the different types of metrics we currently support the following: messages in & out per second, consumer lag, consumer read rate, topic size, replica count, and connector tasks count.
These are defined in the [`Metric`](https://github.com/bakdata/streams-explorer/blob/fe3e766f709bc3d3851eb7a59681ea41b78a84cf/backend/streams_explorer/models/graph.py#L22) model.

> **Use topology endpoint for topic extraction**
> We'd prefer to read the topology dynamically through a REST endpoint exposed by our streaming apps instead of relying on env variables being set via Helm. Do you consider this a reasonable alternative plus could you give a hint where that logic would be supposed to be implemented?

The streams explorer builds upon the idea to generate and update the pipeline graphs via the Kubernetes API without requiring the implementation of additional services, but only common configurations and deployments we easily enable via [streams-bootstrap](https://github.com/bakdata/streams-bootstrap) and [faust-bootstrap](https://github.com/bakdata/faust-bootstrap). Since exposing the topology or rather the topics via a REST endpoint is quite a different approach, we don’t have plans to support this, sorry!

We hope you will find the Streams Explorer useful for your application. If you have any additional questions please let me know!

**Comment by twiechert** [comment]
Thank you for the very elaborate response!
Also very nice that there are already abstractions for the different metrics.

We will certainly poc the the app within our setup and potentially come back with feedback bug reports.
